package:
  name: mpifft4py
  version: "1.0.2"

source:
  git_url: ../../

build:
  number: 24

requirements:
  build:
    - python
    - cython
    - numpy

  run:
    - python
    - numpy
    - scipy
    - mpi4py
    - mpich  #[unix]
    - openmpi ==1.6.3 #[osx]
    - cython
    - pyfftw

test:
  source_files:
    - tests

  requires:
    - pytest
